### ISSUE TITLE
Typo in BellumCivile ?

### ISSUE THREAD

**Issue by PhVerkerk** [CIRCSE/LT4HALA#1]
In the file "Caesar_BellumCivile_LiberII.conllu", I found a surprising "benefficio" with a double-f. At "sent_id 222", you give "non proditi per illum Caesaris benefficio estis conseruati".
I went on the web http://agoraclass.fltr.ucl.ac.be/concordances/caesar_dbcII/lecture/4.htm and in [2,32] I read: "nonne proditi per illum Caesaris beneficio estis conseruati?"
It will have almost no consequences as it is in the training set. But it is supposed to be a "gold standard".

**Comment by RacheleSprugnoli** [comment]
Dear Philippe,
as written in the annotation guidelines, our texts are taken from the Perseus Github repository. There, "benefficio" appears with a double f; see below the complete XML section.

<div type="textpart" subtype="section" n="8"><p><q rend="merge">vosne vero L. Domitium, an vos Domitius deseruit? nonne extremam pati fortunam paratos proiecit ille? non sibi clam vobis salutem fuga petivit? non proditi per illum Caesaris benefficio estis conservati?</q></p></div> 

Best,
Rachele

**Comment by PhVerkerk** [comment]
Yes, for sure ! But the original text PHI/lat0448.txt gives : 
"tunam paratos proiecit ille? non sibi clam vobis salu- 
tem fuga petivit? non proditi per illum Caesaris bene- 
ficio estis conservati? sacramento quidem vos tenere" 
The hyphen at the line-break has been transformed in Perseus text in a "ff", which is undoubtly a mistake. 

The real underlying question is "do we have to propage errors ?" 


De: "chopinesque" <notifications@github.com> 
À: "CIRCSE/LT4HALA" <LT4HALA@noreply.github.com> 
Cc: "Philippe Verkerk" <Philippe.Verkerk@univ-lille1.fr>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 16 Décembre 2019 11:00:19 
Objet: Re: [CIRCSE/LT4HALA] Typo in BellumCivile ? (#1) 



Dear Philippe, 
as written in the annotation guidelines, our texts are taken from the Perseus Github repository. There, "benefficio" appears with a double f; see below the complete XML section. 


vosne vero L. Domitium, an vos Domitius deseruit? nonne extremam pati fortunam paratos proiecit ille? non sibi clam vobis salutem fuga petivit? non proditi per illum Caesaris benefficio estis conservati? 


Best, 
Rachele
